name: Run go test

on:
  workflow_call:
    inputs:
      go-version:
        description: "Set Go version"
        default: 1.22
        type: string
      lint-version:
        description: "Set Lint go version"
        default: v1.54.2
        type: string
      test:
        description: "Enable Go test"
        default: true
        type: boolean
      lint:
        description: "Execute script lint"
        default: true
        type: boolean
      type:
        description: "project type, such as: 'pkg', 'app'"
        default: app
        type: string

jobs:
  script-go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
      - name: Build
        run: go build -v ./...
      - name: App Test
        id: run_app_test
        if: ${{ inputs.test && inputs.type == 'app'}}
        run: go test ./internal/... ./pkg/... -covermode=atomic -coverpkg=./... -count=1 -race -v
      - name: Pkg Test
        id: run_pkg_test
        if: ${{ inputs.test && inputs.type == 'pkg'}}
        run: go test ./... -covermode=atomic -coverpkg=./... -count=1 -race -v
      - name: Linter
        if: ${{ inputs.lint }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ inputs.lint-version }}